### ISSUE TITLE
MiningUPSGrade request

### ISSUE THREAD

**Issue by gnordlan** [Kingdud/Factorio-Mods#9]
Would it be possible for the MiningUPSGrade (giant miner) to be released stand-alone, without the extra dependencies?
I don't understand why it requires EnhancedGridEnergyStores, GattlingPulseLaser, or NuclearRebalance. It doesn't seem like those things are related, and my only interest is the giant mining machine.

I don't understand yet how to do it myself, and obviously I shouldn't steal your work. :)

**Comment by Kingdud** [comment]
? You can? The dependencies are all optional. I basically used the space as free marketing for my other mods. :p

**Comment by gnordlan** [comment]
OOOOOOH! Ok, still learning the mod stuff. Thanks for the feedback!
